apiVersion: v1
kind: Secret
metadata:
  name: ers-server-secrets
  namespace: ers
  labels:
    app: ers
    tier: service
type: Opaque
data:
  HOST: {{ .Values.mysql.host | b64enc }}
  PORT: {{ .Values.mysql.port | b64enc }}
