apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ers-mysql-pvc
  labels:
    app: ers
    tier: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-mysql-deploy
  namespace: ers
  labels:
    app: ers
    tier: data
spec:
  selector:
    matchLabels:
      app: ers
      tier: data
  template:
    metadata:
      name: ers-mysql-deploy
      namespace: ers
      labels:
        app: ers
        tier: data
    spec:
      containers:
        - name: ers-mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
              name: ers-mysql-port
              protocol: TCP
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secrets
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secrets
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_RANDOM_ROOT_PASSWORD
                  name: mysql-secrets
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  mysql -u ${MYSQL_USER} --password=${MYSQL_PASSWORD} -e 'SELECT 1'
            successThreshold: 2
            failureThreshold: 5
            periodSeconds: 15
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ers-mysql-pvc
