apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: ers
spec:
  ports:
    - port: 8200
      targetPort: apm-server-port
      name: apm-server-svc-port
  selector:
    app: es-cluster
    tier: apm
