apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tiller-role
  namespace: ers
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io", "rbac.authorization.k8s.io", "apiextensions.k8s.io/v1beta1"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
  