apiVersion: v1
kind: ConfigMap
metadata:
  name: packetbeat-config
  namespace: kube-system
  labels:
    app: es-cluster
    tier: apm
data:
  packetbeat.yml: |
    setup.dashboards.enabled: true
    setup.template.enabled: true
    packetbeat.interfaces.device: any
    packetbeat.protocols:
    - type: dns
      ports: [53]
      include_authorities: true
      include_additionals: true
    - type: http
      ports: [80, 8000, 8080, 9200]
    - type: mysql
      ports: [3306]
    packetbeat.flows:
      timeout: 30s
      period: 10s
    processors:
      - add_kubernetes_metadata:
          host: ${HOSTNAME}
          indexers:
          - ip_port:
          matchers:
          - field_format:
              format: '%{[ip]}:%{[port]}'

    output.elasticsearch:
      hosts: ['elasticsearch.ers.svc.cluster.local:9200']

    setup.kibana:
      enabled: true
      host: "kibana-svc.ers.svc.cluster.local:80"
