apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: ers
  labels:
    app: ers
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.db.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.db.password | b64enc }}
  MYSQL_DATABASE: {{ .Values.db.name | b64enc }}
  MYSQL_RANDOM_ROOT_PASSWORD: {{ .Values.db.useRandomRootPwd | b64enc }}
