apiVersion: v1
kind: Secret
metadata:
  name: ers-server-secrets
  namespace: ers
  labels:
    app: ers
    tier: service
type: Opaque
stringData:
  HOST: {{ .Values.db.host | b64enc }}
  PORT: {{ .Values.db.port | b64enc }}
